### ISSUE TITLE
Program stalls at 7GB ram usage

### ISSUE THREAD

**Issue by Bilibox** [tonikelope/megabasterd#112]
With some testing I've noticed, both the jar and run for linux break completely when the program reaches ~7.1GB ram usage. At this point uploads are stalled (Kbps instead of MBps). 

This happens for me when uploading ~10 ~20GB files (about 230GB total) @ 2 slots +. First the gui breaks and I am unable to change any settings at all then the network breaks once it hits 7.1GB ram usage.

**Comment by tonikelope** [comment]
Uffff. There could be quite a few things... For starters, could you run MegaBasterd by command console (redirecting the output to a text file)? Let's see if you get any finished memory errors.
On the other hand, when this happens to you, what is the CPU usage? The bottleneck when uploading files to MEGA is not so much the speed of the connection, as the total size you are uploading (each file you upload is encrypted and at the same time generates a CBC-MAC verification code that consumes a lot of CPU in such large files).

I'm waiting for your log.

**Comment by Bilibox** [comment]
https://pastebin.com/D9gYTYmN

I forgot to grab the full log but I was looking at it consistently and it was all the same. 
The only thing that stands out is 
Sep 12, 2019 4:24:04 AM com.tonikelope.megabasterd.ChunkUploader run
SEVERE: null
Sep 12, 2019 4:24:04 AM com.tonikelope.megabasterd.ChunkUploader run
WARNING: pool-7-thread-21 Uploading chunk 8,212 from worker 19 FAILED!...

CPU usage is 100% from the start (Even on 2 slots) I used 20 slots this time. 
also might be because I'm uploading @ 1GBit/s 
For system info
Ram ~ 24GB usable
CPU Info: https://pastebin.com/LXWKB3Bv

**Comment by Bilibox** [comment]
With V6.41 @ 16GB max 8files uploading 160GB

Average speed is cut down quite a bit. though i didnt test again with previous versions so could just be mega (560mbps vs 800+mbps) 

MB seemed to quickily jump to 10GB then slowly make its way to 16GB before reaching 16.8GB ram usage then slowed down but picked right back up to avg speed of 500mbps. then dying and picking back up again. and consistently cycles between the two. 
I did see it hit 17.5GB ram usage when it stalled.
Nothing out of the ordinary from the log.

Gui stays frozen for all of it.

Seems to be on the right track I got to 90GB/160GB uploaded before it became just to slow to continue. (100kbps)

**Comment by tonikelope** [comment]
I have implemented a method that forces to call the Java garbage collector past 70% of available used memory, but I don't know if it will have much impact. I checked the code to see if I could scratch memory from somewhere and it doesn't look easy. Java is not intended to optimize the use of memory I'm afraid. I think you will have to reduce a bit the number of simultaneous uploads and/or slots, sorry.

**Comment by Bilibox** [comment]
it looks like the GC isn't kicking in till it hits MAX ram usage. (6.43) 
Still has the same issues as previously

I tried running it with Shenandoah GC and the results were a lot better. It wasnt kicking in until it hit the max ram usage (20GB) but it would chop it down to ~8GB after each time. Slowly increasing as the upload continued. 
Though I know Shenandoah isn't available in all versions of java. So would be a compatibility issue for some.

I'm more than happy for long term testing of this as increasing the efficiency is always a bonus. I usually always have plenty of things I need to upload to Mega and Megabasterd has been the fastest client for doing so.

**Comment by Bilibox** [comment]
1 File 58GB 20GB(Allotted ram) 20 Slots MB Version 6.44B

20.6GB Ram Usage Garbage collection Started for the first time (Went up to 21GB) then after it was done went back down to 20.3GB

Interface was *more* responsive than normal. Though still not really responsive. Once the upload was nearing completion the interface finally showed it reached 26/58GB. 

Garbage collection started again (21.6GB ram) and seemed to keep looping for some reason. (ran again after 3 minutes.) At this point the upload should have been completed (according to the network usage) but was not showing up in the mega account. ~59k chunks were uploaded for this
Log also showed Completion handle > 
By the end of this it had said "Bye bye" to all 20 upload workers.

After waiting ~7 minutes from when it should have been completed the UI shows 58/58GB uploaded(Still said it was running on UI) at this point CPU usage dipped down to a steady ~80% usage.

After that ~every 2 minutes it was show Forcing Garbage Collector.
Then 20 minutes after Completion handle (was still going through "forcing garbage collection") I noticed ram usage dropped down to 12.5GB (Interface was still showing as it was running but 58/58GB uploaded)  and ~25% cpu usage 

~30 minutes after I got MAC GENERATOR finished MAC CALCULATION waiting for workers to finish uploading (though they were already finished)
Mac Generator Bye bye 
Then the upload showed in the account.

**Comment by tonikelope** [comment]
> Edit: I havent looked around your code too much but I'm guessing the previous chunks data are kept in memory? Would it be possible to flush out the old chunks ~1-5k? or is there a specific reason why you keep them? maybe even writing the data you need to a separate file may alleviate some stress.

Chunks are read from disk, encrypted and uploaded to MEGA. They are not kept in memory. 

I have modified in the last version the code of the ChunkUploader to use a read buffer when reading the chunks of the file. I've tried it and noticed improvements in the average upload speed.

I've eliminated the calls to the garbage collector, because it's something that the JVM already does when it sees fit.

In my tests I have uploaded a 30 GB @ 4GBRAM file and the memory consumption remains "controlled". 

On the MAC GENERATOR it is normal that when the speed of connection is high and the size of the big file, finishes before the file is uploaded that to calculate the code CBC-MAC (that is a very heavy process and that does not allow to take advantage of more than 1 core of the CPU).

I hope the latest version works for you in an acceptable way. I recommend you to restrict to a simultaneous upload (to avoid overhead when reading different files from disk) and leave the slots by default if the speed is acceptable or go up slowly.

I'm going to leave the development of MegaBasterd a little longer because I have little free time.

Regards ;)
